version: '3.8'

services:
  ydb:
    image: ydbplatform/local-ydb:latest
    container_name: ydb
    hostname: ydb
    platform: linux/amd64
    ports:
      - "2135:2135"
      - "2136:2136"
      - "8765:8765"
      - "9092:9092"
    volumes:
      - ./ydb_certs:/ydb_certs
      - ./ydb_data:/ydb_data
    environment:
      - GRPC_TLS_PORT=2135
      - GRPC_PORT=2136
      - MON_PORT=8765
      - YDB_KAFKA_PROXY_PORT=9092
    restart: unless-stopped
    networks:
      - dreamwiki-net

  dream-wiki:
    hostname: dream-wiki
    container_name: dream-wiki
    build:
      context: ../../backend/services/dream-wiki
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8080
      - INFERENCE_API_URL=http://inference:8000
      - LOG_MODE=dev
      - YDB_DSN=grpc://ydb:2136/?database=/local
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - YWIKI_TOKEN=${YWIKI_TOKEN}
      - YANDEX_CLOUD_ORG_ID=${YANDEX_CLOUD_ORG_ID}
    ports:
      - "8081:8080"
    networks:
      - dreamwiki-net
    depends_on:
      - ydb
      - inference

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dreamwiki-net
    depends_on:
      - dream-wiki

  inference:
    build:
      context: ../../backend/services/inference
      dockerfile: Dockerfile
    ports:
      - "8082:8000"
    networks:
      - dreamwiki-net
    restart: unless-stopped

networks:
  dreamwiki-net:
    driver: bridge
