version: '3.8'

services:
  ydb:
    image: ghcr.io/ydb-platform/local-ydb:nightly
    ports:
      - "2136:2136"  # Основной порт YDB
      - "8765:8765"  # Порт веб-интерфейса
      - "5432:5432"  # Порт PostgreSQL-совместимого режима
    environment:
      - YDB_USE_IN_MEMORY_PDISKS=true
      - GRPC_PORT=2136
      - GRPC_TLS_PORT=2135
      - MON_PORT=8765
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${YDB_PG_USER:-root}
      - POSTGRES_PASSWORD=${YDB_PG_PASSWORD:-1234}
      - YDB_DEFAULT_LOG_LEVEL=NOTICE
      - YDB_EXPERIMENTAL_PG=1
    networks:
      - dreamwiki-net

  dream-wiki:
    hostname: dream-wiki
    container_name: dream-wiki
    build:
      context: ../../backend/services/dream-wiki
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    networks:
      - dreamwiki-net
    depends_on:
      - ydb

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - dreamwiki-net
    depends_on:
      - dream-wiki

networks:
  dreamwiki-net:
    driver: bridge
