openapi: 3.0.3
info:
  title: Dream Wiki API
  description: API Specification for Dream Wiki API
  version: 0.0.1

servers:
  - url: http://localhost:8080/api
    description: Development server

paths:
  /v1/search:
    post:
      summary: Поиск информации в базе знаний
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1SearchRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1SearchResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/diagnostic-info/get:
    post:
      summary: Диагностическая информация и исходный код последней ревизии
      operationId: getDiagnosticInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1DiagnosticInfoGetRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1DiagnosticInfoGetResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/indexate-page:
    post:
      summary: Принудительно проиндексировать страницу. Синхронная ручка
      operationId: indexatePage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1IndexatePageRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1IndexatePageResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/ywiki/add-page:
    post:
      summary: Добавление новой страницы из ywiki
      operationId: ywikiAddPage
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1YwikiAddPageRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1YwikiAddPageResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/github/account-pr:
    post:
      summary: Обновить информацию по PR из github
      operationId: githubAccountPR
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1GithubAccountPRRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1GithubAccountPRResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/ywiki/fetch-all:
    post:
      summary: Выгрузить все известные статьи с Яндекс Wiki и обновить индексацию
      operationId: ywikiFetchAll
      responses:
        "200":
          description: OK
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

  /v1/integration-logs/get:
    post:
      summary: Получить логи указанной интеграции
      operationId: integrationLogsGet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/V1IntegrationLogsGetRequest"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/V1IntegrationLogsGetResponse"
        "500":
          $ref: "#/components/responses/InternalErrorResponse"

components:
  schemas:
    V1SearchRequest:
      type: object
      properties:
        query:
          type: string
          description: Поисковый запрос на естественном языке
      required:
        - query

    V1SearchResponse:
      type: object
      properties:
        result_items:
          type: array
          items:
            $ref: "#/components/schemas/SearchResultItem"
      required:
        - result_items

    V1DiagnosticInfoGetRequest:
      type: object
      properties:
        page_id:
          type: string
          format: uuid
      required:
        - page_id

    V1DiagnosticInfoGetResponse:
      type: object
      properties:
        page:
          $ref: "#/components/schemas/Page"
      required:
        - page

    V1IndexatePageRequest:
      type: object
      properties:
        page_id:
          type: string
          format: uuid
      required:
        - page_id

    V1IndexatePageResponse:
      type: object
      properties:
        page_id:
          type: string
          format: uuid
      required:
        - page_id

    V1YwikiAddPageRequest:
      type: object
      properties:
        page_url:
          type: string
          format: uri
      required:
        - page_url

    V1YwikiAddPageResponse:
      type: object

    V1GithubAccountPRRequest:
      type: object
      properties:
        pr_url:
          type: string
          format: uri
      required:
        - pr_url

    V1GithubAccountPRResponse:
      type: object

    V1IntegrationLogsGetRequest:
      type: object
      properties:
        integration_id:
          $ref: "#/components/schemas/IntegrationID"
        cursor:
          type: string
      required:
        - integration_id

    V1IntegrationLogsGetResponse:
      type: object
      properties:
        cursor:
          type: string
        log_fields:
          type: array
          items:
            type: string
      required:
        - cursor
        - log_fields

    SearchResultItem:
      type: object
      properties:
        page_id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
          description: Описание поискового результата в формате MD
      required:
        - title
        - description
        - page_id

    Page:
      type: object
      properties:
        page_id:
          type: string
          format: uuid
        content:
          type: string
        title:
          type: string
      required:
        - page_id
        - content
        - title

    ErrorResponseBody:
      type: object
      properties:
        message:
          type: string
      required:
        - message

    IntegrationID:
      type: string
      enum:
        - ywiki
        - github

  responses:
    InternalErrorResponse:
      description: 500 Internal error
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponseBody"
