openapi: 3.0.3
info:
  title: Dream Wiki API
  description: API Specification for Dream Wiki API
  version: 0.0.1

servers:
  - url: http://localhost:8080/api
    description: Development server

paths:
  /v1/search:
    post:
      summary: Поиск информации в базе знаний
      operationId: search
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1SearchRequest'
      responses:
        '200':
          description: Успешный поиск
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1SearchResponse'

  /v1/diagnostic-info/get:
    post:
      summary: Получение диагностической информации по странице
      operationId: getDiagnosticInfo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1DiagnosticInfoGetRequest'
      responses:
        '200':
          description: Диагностическая информация
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1DiagnosticInfoGetResponse'
  
  /v1/indexate-page:
    post:
      summary: Принудительная индексация страницы
      operationId: indexate
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/V1IndexatePageRequest'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/V1IndexatePageResponse'

components:
  schemas:
    V1SearchRequest:
      type: object
      properties:
        query:
          type: string
          description: Запрос
      required:
        - query

    V1SearchResponse:
      type: object
      properties:
        result_items:
          type: array
          items:
            $ref: '#/components/schemas/SearchResultItem'
      required:
        - result_items

    SearchResultItem:
      type: object
      properties:
        title:
          type: string
          description: Заголовок
        description:
          type: string
          description: Описание
        page_id:
          type: string
          description: Идентификатор страницы
      required:
        - title
        - description
        - page_id

    V1DiagnosticInfoGetRequest:
      type: object
      properties:
        page_id:
          type: string
          description: Идентификатор страницы
      required:
        - page_id

    V1DiagnosticInfoGetResponse:
      type: object
      properties:
        page_id:
          type: string
        content:
          type: string
        title:
          type: string
        created_at:
          type: string
          format: date-time
      required:
        - page_id
        - content
        - title
        - created_at
    
    V1IndexatePageRequest:
      type: object
      properties:
        page_id:
          type: string
      required:
        - page_id

    V1IndexatePageResponse:
      type: object
      properties:
        page_id:
          type: string
      required:
        - page_id
